export const data=[
        {
          "sl_no": 1,
          "certificate_no": "ABC123",
          "admn_no": 123456,
          "name": "John Doe",
          "course": "B.Tech",
          "branch": "Computer",
          "ogpa": 8.5,
          "ogpa_h": 8.8,
          "final_ogpa": 8.7,
          "division": "First",
          "date_of_result": "2024-04-13",
          "yop": 2024,
          "dept_id": "001",
          "course_id": "101",
          "branch_id": "201",
          "deptnm": "Engineering"
        },
        {
          "sl_no": 2,
          "certificate_no": "XYZ456",
          "admn_no": 654321,
          "name": "Jane Smith",
          "course": "B.Sc",
          "branch": "Physics",
          "ogpa": 7.9,
          "ogpa_h": 8.2,
          "final_ogpa": 8.0,
          "division": "Second",
          "date_of_result": "2024-04-13",
          "yop": 2024,
          "dept_id": "002",
          "course_id": "102",
          "branch_id": "202",
          "deptnm": "Science"
        },
        {
          "sl_no": 3,
          "certificate_no": "DEF789",
          "admn_no": 987654,
          "name": "Alice Johnson",
          "course": "B.E",
          "branch": "Civil",
          "ogpa": 7.2,
          "ogpa_h": 7.5,
          "final_ogpa": 7.4,
          "division": "Second",
          "date_of_result": "2024-04-13",
          "yop": 2024,
          "dept_id": "001",
          "course_id": "103",
          "branch_id": "203",
          "deptnm": "Engineering"
        },{
            "sl_no": 4,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          },{
            "sl_no": 5,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          },{
            "sl_no": 6,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          },{
            "sl_no": 7,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          },{
            "sl_no": 8,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          },{
            "sl_no": 9,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          },{
            "sl_no": 10,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          },{
            "sl_no": 11,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          },{
            "sl_no": 12,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          },{
            "sl_no": 13,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          },
          {
            "sl_no": 14,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 15,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 16,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          },{
            "sl_no": 17,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 18,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 19,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 20,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 21,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 22,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 23,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 24,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 25,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 26,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
          ,{
            "sl_no": 27,
            "certificate_no": "ABC123",
            "admn_no": 123456,
            "name": "John Doe",
            "course": "B.Tech",
            "branch": "Computer",
            "ogpa": 8.5,
            "ogpa_h": 8.8,
            "final_ogpa": 8.7,
            "division": "First",
            "date_of_result": "2024-04-13",
            "yop": 2024,
            "dept_id": "001",
            "course_id": "101",
            "branch_id": "201",
            "deptnm": "Engineering"
          }
      ]
      